# Alacritty Configuration File

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[window]
# Background transparency (0.0 = fully transparent, 1.0 = fully opaque)
opacity = 0.7

# Window dimensions in terms of terminal rows/columns
dimensions = { columns = 80, lines = 24 }

# Padding around the terminal (in pixels)
padding = { x = 0, y = 0 }

# Decorations: "Full", "None", "Transparent", "Buttonless"
# decorations = "Full"

# Title of the terminal window
title = "Alacritty"

[colors.primary]
# Force the background to be black so it’s easier to read
background = "#000000"

[font]
# Use JetBrains Mono Nerd Font
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }
size = 11.5

[scrolling]
# Scrollback history size
history = 10000

# Scrolling multiplier
multiplier = 3

[cursor]
# Cursor configuration
style = "Block"  # Options: "Block", "Underline", "Beam"

[keyboard]
# Keybindings configuration
bindings = [
    # Toggle fullscreen with F11
    { key = "F11", action = "ToggleFullscreen" },
    { key = "NumpadEnter", mods = "None", action = "ReceiveChar"},
    { key = "Tab", mods = "Alt", action = "ToggleViMode"},
    { key = "v", mods = "Control", action = "Paste"}
]

[env]
term = "xterm-256color"
